/**
 * Applies the necessary Gradle plugins for the application.
 */
plugins {
    alias(libs.plugins.android.application) // The Android Application plugin.
    alias(libs.plugins.kotlin.android)     // The Kotlin Android plugin.
    alias(libs.plugins.kotlin.compose)     // The Kotlin Compose plugin.
    alias(libs.plugins.kotlin.serialization) // The Kotlin Serialization plugin.
}

/**
 * Configures Android-specific settings for the application.
 */
android {
    // The application's package name.
    namespace = "com.ksh.esp32app"
    // The API level to compile the application against.
    compileSdk = 34

    defaultConfig {
        applicationId = "com.ksh.esp32app" // The unique identifier for the application.
        minSdk = 29 // The minimum API level required to run the application.
        targetSdk = 34 // The API level the application is designed to run on.
        versionCode = 1 // The version code of the application.
        versionName = "1.0" // The version name of the application.

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner" // The test runner for Android instrumented tests.
    }

    buildTypes {
        release {
            isMinifyEnabled = false // Whether to enable code shrinking for the release build.
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            ) // The ProGuard configuration files for the release build.
        }
    }
    compileOptions {
        // The Java language level for the source code.
        sourceCompatibility = JavaVersion.VERSION_11
        // The Java language level for the generated bytecode.
        targetCompatibility = JavaVersion.VERSION_11
    }
    kotlinOptions {
        // The JVM target version for the Kotlin compiler.
        jvmTarget = "11"
    }
    buildFeatures {
        // Enables Jetpack Compose for the application.
        compose = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.1"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

/**
 * Declares the dependencies for the application.
 */
dependencies {
    // Core Kotlin libraries
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)

    // Jetpack Compose libraries
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.material.icons.extended)

    // USB Serial library
    implementation(libs.usb.serial.android)

    // DataStore for settings persistence
    implementation(libs.datastore.preferences)

    // Kotlin Serialization for JSON processing
    implementation(libs.kotlinx.serialization.json)

    // Testing libraries
    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)

    // Debugging libraries
    debugImplementation(libs.androidx.compose.ui.tooling)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
}